export const translations = {
  'nav.about': 'परिचय',
  'nav.features': 'विशेषताएँ',
  'nav.impact': 'प्रभाव',
  'nav.contact': 'संपर्क',
  'nav.login': 'लॉगिन',
  'nav.get_started': 'शुरू करें',
  'hero.title': 'स्थायी कृषि को मज़ेदार, लाभकारी और आकर्षक बनाएं',
  'hero.description': 'ईकोवेटर्स से जुड़ें, सीखें, योगदान दें और हमारे ग्रह पर वास्तविक प्रभाव डालें गेमिफाइड चुनौतियों, सामुदायिक कार्यों और रीयल-टाइम ट्रैकिंग के माध्यम से।',
  'hero.button': 'शुरू करें',
  'about.title': 'ईकोवेटर्स के बारे में',
  'about.description': 'ईकोवेटर्स एक गमिफाइड डिजिटल प्लेटफ़ॉर्म है जो किसानों को पर्यावरण-अनुकूल प्रथाओं को अपनाने के लिए प्रेरित करता है। ईकोवेटर्स किसानों को - विशेष रूप से युवा किसानों को - अस्थिर अभ्यासी से प्रगतिशील कृषि की ओर स्थानांतरित करने के लिए प्रेरित करता है।',
  'about.goal': 'हमारा लक्ष्य स्थायी कृषि को केवल आवश्यकता नहीं, बल्कि एक रोमांचक यात्रा बनाना है - इसे खेल, आंदोलन और जीवनशैली में बदलना।',
  'about.stats.active_farmers': '10,000+',
  'about.stats.active_farmers_label': 'सक्रिय किसान',
  'about.stats.agri_experts': '500+',
  'about.stats.agri_experts_label': 'कृषि विशेषज्ञ',
  'about.stats.trees_planted': '50,000+',
  'about.stats.trees_planted_label': 'रोपे गए पेड़',
  'about.stats.challenges_completed': '100,000+',
  'about.stats.challenges_completed_label': 'पूरा की गई चुनौतियाँ',
  'features.title': 'प्लेटफ़ॉर्म की विशेषताएँ',
  'features.gamified_learning': 'गमिफाइड लर्निंग',
  'features.gamified_learning_description': 'पर्यावरण विषयों को सीखते हुए XP, बैज और लीडरबोर्ड अर्जित करें।',
  'features.community_chat': 'सामुदायिक चैट',
  'features.community_chat_description': 'सहकर्मियों के साथ वास्तविक समय में संवाद करें - पाठ, छवि, ऑडियो और वीडियो सहित।',
  'features.environmental_challenges': 'पर्यावरणीय चुनौतियाँ',
  'features.environmental_challenges_description': 'क्विज, गतिविधियाँ और वास्तविक दुनिया की पर्यावरणीय क्रियाओं में भाग लें।',
  'features.micro_courses': 'सूक्ष्म-पाठ्यक्रम',
  'features.micro_courses_description': 'प्रगति ट्रैकिंग और प्रमाण पत्र के साथ बाइट-साइज़ पाठ्यक्रमों के माध्यम से सीखें।',
  'features.events': 'घटनाएँ',
  'features.events_description': 'सहकारी समितियों, एनजीओ, और सामुदायिक भागीदारों द्वारा आयोजित पर्यावरणीय घटनाओं में शामिल हों।',
  'features.geotag_uploads': 'जियोटैग अपलोड',
  'features.geotag_uploads_description': 'स्थान-आधारित सत्यापन के साथ अपने कार्यों का दस्तावेज़ीकरण करें।',
  'impact.title': 'हमारा पर्यावरणीय प्रभाव',
  'impact.metrics.co2_offset': '25,000',
  'impact.metrics.co2_offset_label': 'CO₂ ऑफ़सेट (टन)',
  'impact.metrics.waste_recycled': '75,000',
  'impact.metrics.waste_recycled_label': 'पुनःचक्रित कचरा (किग्रा)',
  'impact.metrics.water_saved': '120,000',
  'impact.metrics.water_saved_label': 'संरक्षित जल (लीटर)',
  'roles.title': 'कौन जुड़ सकता है?',
  'roles.farmer': 'किसान',
  'roles.farmer_description': 'सीखें, चुनौतियों में भाग लें, इनाम पाएं, और वास्तविक प्रभाव डालें।',
  'roles.agri_expert': 'कृषि विशेषज्ञ',
  'roles.agri_expert_description': 'चुनौतियाँ बनाएं, किसानों की प्रगति की निगरानी करें, और पर्यावरणीय गतिविधियों की सुविधा प्रदान करें।',
  'roles.cooperative_admin': 'सहकारी समिति प्रशासक',
  'roles.cooperative_admin_description': 'अपनी समिति की पर्यावरणीय पहल का प्रबंधन करें और समग्र प्रभाव को ट्रैक करें।',
  'roles.ngo': 'एनजीओ',
  'roles.ngo_description': 'आयोजन करें, किसानों के साथ सहयोग करें, और अपने पर्यावरणीय प्रभाव का विस्तार करें।',
  'roles.company': 'कंपनियाँ',
  'roles.company_description': 'कार्बन क्रेडिट और विज्ञापन साझेदारी के माध्यम से पर्यावरणीय शिक्षा का समर्थन करें।',
  'contact.title': 'संपर्क करें',
  'contact.email': 'ecovators.sih@gmail.com',
  'contact.phone': '+91 8141829957',
  'contact.address': 'अहमदाबाद',
  'contact.send_message': 'संदेश भेजें',
  'footer.platform': 'प्लेटफ़ॉर्म',
  'footer.features': 'विशेषताएँ',
  'footer.how_it_works': 'कैसे काम करता है',
  'footer.pricing': 'मूल्य',
  'footer.faq': 'सामान्य प्रश्न',
  'footer.resources': 'संसाधन',
  'footer.blog': 'ब्लॉग',
  'footer.guides': 'मार्गदर्शिकाएँ',
  'footer.events': 'घटनाएँ',
  'footer.support': 'सहायता',
  'footer.company': 'कंपनी',
  'footer.about_us': 'हमारे बारे में',
  'footer.careers': 'करियर',
  'footer.partners': 'सहयोगी',
  'footer.contact': 'संपर्क',
  'footer.legal': 'कानूनी',
  'footer.terms_of_service': 'सेवा की शर्तें',
  'footer.privacy_policy': 'गोपनीयता नीति',
  'footer.cookie_policy': 'कुकी नीति',
  'footer.gdpr': 'GDPR',
  'footer.copyright': '© 2025 ईकोवेटर्स. सर्वाधिकार सुरक्षित।',
  'role_modal.title': 'अपना रोल चुनें',
  'role_modal.description': 'जारी रखने के लिए कृपया अपना रोल चुनें।',
  'role_modal.farmer': 'किसान',
  'role_modal.farmer_description': 'चुनौतियों में भाग लें, इनाम कमाएँ, पर्यावरणीय प्रभाव ट्रैक करें',
  'role_modal.agri_expert': 'कृषि विशेषज्ञ',
  'role_modal.agri_expert_description': 'चुनौतियाँ बनाएं, किसान प्रगति की निगरानी करें, लर्निंग की सुविधा दें',
  'role_modal.cooperative_admin': 'सहकारी समिति',
  'role_modal.cooperative_admin_description': 'पर्यावरणीय पहलों का प्रबंधन करें और प्रभाव ट्रैक करें',
  'role_modal.ngo': 'एनजीओ',
  'role_modal.ngo_description': 'आयोजन करें, किसानों के साथ सहयोग करें, प्रभाव बढ़ाएँ',
  'role_modal.company': 'कंपनी',
  'role_modal.company_description': 'भागीदारी के माध्यम से सततता का समर्थन करें',
  'role_modal.government': 'सरकार',
  'role_modal.government_description': 'पर्यावरणीय पहलों और कार्बन क्रेडिट कार्यक्रम की निगरानी करें',
  'login_modal.title': 'लॉगिन',
  'login_modal.description': 'ईमेल और पासवर्ड से साइन इन करें',
  'login_modal.login_button': 'लॉगिन',
  'login_modal.or_login_with': 'या लॉगिन करें',
  // --- Student Dashboard UI ---
  'nav.title': 'ईकोवेटर्स',
  'nav.home': 'होम',
  'nav.logout': 'लॉगआउट',
  'student.nav.profile': 'प्रोफाइल',
  'student.nav.challenges': 'चुनौतियाँ',
  'student.nav.learning': 'अधिगम',
  'student.nav.community': 'सामुदायिक',
  'student.nav.events': 'घटनाएँ',
  // Sidebar
  'student.level': 'स्तर',
  'student.streak': 'दिन की निरंतरता',
  'student.xp_points': 'XP अंक',
  'student.carbon_credits': 'कार्बन क्रेडिट्स',
  'student.to_next_level': 'अगले स्तर तक',
  'student.quick_actions': 'त्वरित क्रियाएँ',
  'student.quick_actions.start_task': "आज का कार्य प्रारंभ करें",
  'student.quick_actions.upload_proof': 'प्रमाण अपलोड करें',
  'student.quick_actions.download_certificate': 'प्रमाणपत्र डाउनलोड करें',
  'student.badges': 'बैजेस',
  'student.badge.tree_guardian': 'वृक्ष रक्षक',
  'student.badge.plastic_free_hero': 'प्लास्टिक-मुक्त हीरो',
  'student.badge.water_warrior': 'जल योद्धा',
  'student.badge.energy_saver': 'ऊर्जा बचतकर्ता',
  // Profile/Eco Impact
  'student.eco_impact': 'ईको इम्पैक्ट',
  'student.trees_planted': 'रोपे गए पेड़',
  'student.waste_reduced': 'घटाया गया कचरा',
  'student.water_saved': 'संरक्षित जल',
  'student.co2_offset': 'CO₂ ऑफ़सेट',
  // Goals
  'student.weekly_goals': 'साप्ताहिक लक्ष्य',
  'student.goal.complete_challenges': '3 चुनौतियाँ पूर्ण करें',
  'student.goal.study_micro_course': 'माइक्रो-पाठ्यक्रम 40% पढ़ें',
  'student.goal.maintain_streak': 'निरंतरता बनाए रखें',
  // Challenges Section
  'student.active_challenges': 'सक्रिय चुनौतियाँ',
  'student.challenge.plant_tree': 'पेड़ लगाने की चुनौती',
  'student.challenge.plant_tree_desc': '+50 XP और +20 कार्बन क्रेडिट्स अर्जित करें',
  'student.challenge.join': 'जॉइन करें',
  'student.challenge.water_conservation': 'जल संरक्षण',
  'student.challenge.water_conservation_desc': 'इस सप्ताह 50 लीटर जल बचाएँ',
  'student.challenge.upload_proof': 'प्रमाण अपलोड करें',
  'student.challenge.pending': 'लंबित',
  'student.challenge.plastic_reduction': 'प्लास्टिक में कमी',
  'student.challenge.plastic_reduction_desc': 'एक सप्ताह प्लास्टिक-मुक्त',
  'student.challenge.approved': 'स्वीकृत',
  // Micro-Courses
  'student.micro_courses': 'माइक्रो-पाठ्यक्रम',
  'student.course.climate_basics': 'जलवायु की मूल बातें',
  'student.course.climate_basics_desc': 'जलवायु परिवर्तन और क्रियाओं की प्रस्तावना',
  'student.course.water_conservation': 'जल संरक्षण',
  'student.course.water_conservation_desc': 'स्मार्ट जल उपयोग',
  'student.course.waste_management': 'कचरा प्रबंधन',
  'student.course.waste_management_desc': 'छँटाई और पुनर्चक्रण',
  'student.continue_learning': 'सीखना जारी रखें',
  // Community/feed/chat
  'community.feed': 'हैक्स और समाचार',
  'community.post.composer.placeholder': 'कोई हैक, फ़ोटो या खबर साझा करें...',
  'community.chat': 'सामुदायिक चैट',
  'community.chat.input.placeholder': 'संदेश लिखें...',
  // Events/Uploads
  'events.upload.title': 'जियोटैग के साथ अपलोड',
  'events.upload.get_location': 'स्थान प्राप्त करें',
  'events.upload.submit': 'प्रमाण सबमिट करें',
  'events.upload.hint': 'आपके प्रमाण को कृषि विशेषज्ञ जाँचेंगे व अनुमोदन/अस्वीकृति देंगे।',
  // Leaderboard/Notifications/Footer
  'student.leaderboard': 'लीडरबोर्ड',
  'student.notifications': 'सूचनाएँ',
  'footer.farmer.title': 'किसान',
  'footer.farmer.challenges': 'चुनौतियाँ',
  'footer.farmer.learning': 'अधिगम',
  'footer.farmer.leaderboard': 'लीडरबोर्ड',
  'footer.community.title': 'सामुदायिक',
  'footer.community.chat': 'चैट',
  'footer.community.events': 'घटनाएँ',
  'footer.community.support': 'सहायता',
  'footer.legal.title': 'कानूनी',
  'footer.legal.terms': 'शर्तें',
  'footer.legal.privacy': 'गोपनीयता',
  // --- Admin Dashboard ---
  'admin.nav.dashboard': 'डैशबोर्ड',
  'admin.nav.analytics': 'एनालिटिक्स',
  'admin.nav.transactions': 'लेन-देन',
  'admin.nav.management': 'प्रबंधन',
  'admin.nav.approvals': 'अनुमोदन',
  'admin.quick_actions': 'त्वरित क्रियाएँ',
  'admin.quick_actions.carbon_calculator': 'कार्बन कैलकुलेटर',
  'admin.quick_actions.export_data': 'डेटा एक्सपोर्ट (PDF)',
  'admin.quick_actions.add_agri_expert': 'कृषि-विशेषज्ञ जोड़ें',
  'admin.quick_actions.add_farmer': 'किसान जोड़ें',
  'admin.quick_actions.manage_content': 'सामग्री प्रबंधन',
  'admin.recent_achievements': 'हाल की उपलब्धियाँ',
  'admin.overview': 'संगठन का अवलोकन',
  'admin.stats.total_farmers': 'कुल किसान',
  'admin.stats.active_agri_experts': 'सक्रिय कृषि-विशेषज्ञ',
  'admin.stats.departments': 'विभाग',
  'admin.stats.engagement_rate': 'सक्रियता दर',
  'admin.environmental_impact': 'पर्यावरणीय प्रभाव',
  'admin.impact.trees_planted': 'रोपे गए पेड़',
  'admin.impact.waste_reduced': 'घटाया गया कचरा (किग्रा)',
  'admin.impact.water_saved': 'संरक्षित जल (लीटर)',
  'admin.impact.co2_offset': 'CO₂ ऑफ़सेट (किग्रा)',
  'admin.department_performance': 'फसल प्रदर्शन',
  'admin.analytics_overview': 'एनालिटिक्स अवलोकन',
  'admin.analytics.active_farmers': 'सक्रिय किसान',
  'admin.analytics.avg_completion': 'औसत पूर्णता',
  'admin.analytics.avg_time_spent': 'औसत समय व्यतीत',
  'admin.analytics.submissions': 'सबमिशन',
  'admin.company_transactions': 'कंपनी लेन-देन',
  'admin.government_transactions': 'सरकारी लेन-देन',
  'admin.teacher_management': 'कृषि-विशेषज्ञ प्रबंधन',
  'admin.farmer_management': 'किसान प्रबंधन',
  'admin.content_management': 'सामग्री प्रबंधन',
  'admin.notifications': 'सूचनाएँ',
  'admin.ngo_event_approvals': 'एनजीओ इवेंट अनुमोदन',

  // --- Company Dashboard ---
  'company.nav.dashboard': 'डैशबोर्ड',
  'company.nav.marketplace': 'कार्बन मार्केटप्लेस',
  'company.nav.advertisement': 'विज्ञापन',
  'company.nav.transactions': 'लेन-देन',
  'company.nav.analytics': 'एनालिटिक्स',
  'company.quick_actions.title': 'त्वरित क्रियाएँ',
  'company.quick_actions.buy_carbon_credits': 'कार्बन क्रेडिट खरीदें',
  'company.quick_actions.create_campaign': 'अभियान बनाएं',
  'company.quick_actions.view_analytics': 'एनालिटिक्स देखें',
  'company.quick_actions.download_reports': 'रिपोर्ट डाउनलोड करें',
  'company.impact_overview': 'पर्यावरणीय प्रभाव',
  'company.impact.co2_offset': 'CO₂ ऑफ़सेट',
  'company.impact.trees_supported': 'समर्थित पेड़',
  'company.marketplace.featured_credits': 'विशिष्ट कार्बन क्रेडिट्स',
  'company.marketplace.available_credits': 'उपलब्ध क्रेडिट्स',
  'company.marketplace.purchase_credits': 'क्रेडिट्स खरीदें',
  'company.regional_performance.title': 'क्षेत्रीय प्रदर्शन',
  'company.school_directory.title': 'गाँव निर्देशिका',
  'company.school_directory.search_villages': 'गाँव खोजें...',
  'company.teacher_directory.title': 'कृषि-विशेषज्ञ एनालिटिक्स',
  'company.teacher_directory.active_agri_experts': 'सक्रिय कृषि-विशेषज्ञ',
  'company.teacher_directory.participation_rate': 'भागीदारी दर',
  'company.teacher_directory.avg_rating': 'औसत रेटिंग',
  'company.participation_analytics.title': 'भागीदारी एनालिटिक्स',
  'company.participation_analytics.active_farmers': 'सक्रिय किसान',
  'company.participation_analytics.avg_completion_rate': 'औसत पूर्णता दर',

  // --- Government Dashboard ---
  'government.nav.dashboard': 'डैशबोर्ड',
  'government.nav.transactions': 'लेन-देन',
  'government.nav.analytics': 'एनालिटिक्स',
  'government.nav.reports': 'रिपोर्ट्स',
  'government.quick_actions.title': 'त्वरित क्रियाएँ',
  'government.quick_actions.view_reports': 'रिपोर्ट्स देखें',
  'government.quick_actions.download_data': 'डेटा डाउनलोड करें',
  'government.quick_actions.export_analytics': 'एनालिटिक्स एक्सपोर्ट करें',
  'government.overview': 'अवलोकन',
  'government.overview.villages': 'गाँव',
  'government.overview.active_farmers': 'सक्रिय किसान',
  'government.overview.active_agri_experts': 'सक्रिय कृषि-विशेषज्ञ',
  'government.overview.ngo_partners': 'एनजीओ सहयोगी',
  'government.regional_performance.title': 'क्षेत्रीय प्रदर्शन अवलोकन',
  'government.transactions.title': 'लेन-देन',
  'government.transactions.date_time': 'तिथि और समय',
  'government.transactions.villages': 'गाँव',
  'government.transactions.data_type': 'डेटा प्रकार',
  'government.transactions.amount': 'राशि',
  'government.transactions.actions': 'क्रिया',
  'government.analytics.title': 'एनालिटिक्स',
  'government.analytics.national_participation_change': 'राष्ट्रीय भागीदारी परिवर्तन',
  'government.analytics.environmental_impact': 'पर्यावरणीय प्रभाव',
  'government.analytics.budget_utilization': 'बजट उपयोग',
  'government.reports.title': 'रिपोर्ट्स',
  'government.reports.download_customized_reports': 'मनपसंद रिपोर्ट डाउनलोड करें',
  'government.reports.recent_reports': 'हाल की रिपोर्ट्स',

  // --- NGO Dashboard ---
  'ngo.nav.dashboard': 'डैशबोर्ड',
  'ngo.nav.events': 'इवेंट्स',
  'ngo.nav.schools': 'गाँव',
  'ngo.nav.impact': 'प्रभाव',
  'ngo.quick_actions': 'त्वरित क्रियाएँ',
  'ngo.quick_actions.create_event': 'इवेंट बनाएं',
  'ngo.quick_actions.contact_villages': 'गाँव संपर्क करें',
  'ngo.quick_actions.generate_report': 'रिपोर्ट बनाएँ',
  'ngo.impact_summary': 'प्रभाव सारांश',
  'ngo.impact.events_organized': 'आयोजित इवेंट्स',
  'ngo.impact.villages_partnered': 'सहयोगी गाँव',
  'ngo.impact.farmers_reached': 'उपलब्ध किसान',
  'ngo.dashboard.overview': 'डैशबोर्ड अवलोकन',
  'ngo.event_management': 'इवेंट प्रबंधन',
  'ngo.event_management.add_event': 'नया इवेंट जोड़ें',
  'ngo.event_management.upcoming': 'आगामी',
  'ngo.event_management.past': 'पूर्व',
  'ngo.event_management.draft': 'ड्राफ्ट',
  'ngo.schools_section': 'साझेदार गाँव व सोसायटी',
  'ngo.schools_section.search_villages': 'गाँव खोजें...',
  'ngo.schools_section.active': 'सक्रिय',
  'ngo.schools_section.pending': 'लंबित',
  'ngo.schools_section.contact': 'संपर्क करें',
  'ngo.impact_analytics': 'पर्यावरणीय प्रभाव एनालिटिक्स',
  'ngo.impact_analytics.monthly': 'मासिक',
  'ngo.impact_analytics.yearly': 'वार्षिक',
  'ngo.impact_analytics.all_time': 'सर्वकालिक',
  'ngo.impact_analytics.overall_impact': 'कुल पर्यावरणीय प्रभाव',
  'ngo.impact_analytics.carbon_footprint': 'कार्बन फुटप्रिंट में कमी',
  'ngo.impact_analytics.waste_management': 'कचरा प्रबंधन',
  'ngo.impact_analytics.water_conservation': 'जल संरक्षण',
  'ngo.impact_analytics.trees_planted': 'रोपे गए पेड़',
  'ngo.impact_analytics.export': 'रिपोर्ट एक्सपोर्ट करें',
  'ngo.impact_analytics.export_pdf': 'PDF रिपोर्ट',
  'ngo.impact_analytics.export_excel': 'एक्सेल डेटा',
  'ngo.impact_analytics.export_image': 'इन्फोग्राफिक',

  // --- Teacher Dashboard ---
  'teacher.nav.dashboard': 'डैशबोर्ड',
  'teacher.nav.farmers': 'किसान',
  'teacher.nav.challenges': 'चुनौतियाँ',
  'teacher.nav.content': 'सामग्री',
  'teacher.nav.analytics': 'एनालिटिक्स',
  'teacher.stats.title': 'त्वरित आंकड़े',
  'teacher.stats.total_farmers': 'कुल किसान',
  'teacher.stats.active_farmers': 'सक्रिय किसान',
  'teacher.stats.pending_reviews': 'लंबित समीक्षा',
  'teacher.stats.avg_completion': 'औसत पूर्णता',
  'teacher.actions.title': 'त्वरित क्रियाएँ',
  'teacher.actions.create_challenge': 'चुनौती बनाएं',
  'teacher.actions.add_news': 'समाचार जोड़ें',
  'teacher.actions.create_event': 'इवेंट बनाएं',
  'teacher.actions.add_microcourse': 'माइक्रो-पाठ्यक्रम जोड़ें',
  'teacher.dashboard.impact_overview': 'पर्यावरणीय प्रभाव अवलोकन',
  'teacher.dashboard.trees_planted': 'रोपे गए पेड़',
  'teacher.dashboard.waste_reduced': 'घटाया गया कचरा (किग्रा)',
  'teacher.dashboard.water_saved': 'संरक्षित जल (लीटर)',
  'teacher.dashboard.co2_offset': 'CO₂ ऑफ़सेट (किग्रा)',
  'teacher.dashboard.recent_activity': 'हाल की गतिविधि',
  'teacher.pending_reviews': 'लंबित समीक्षा',
  'teacher.analytics.farmers_analytics': 'किसान एनालिटिक्स',
  'teacher.analytics.active_farmers': 'सक्रिय किसान',
  'teacher.analytics.avg_completion_rate': 'औसत पूर्णता दर',
  'teacher.challenge_management': 'चुनौती प्रबंधन',
  'teacher.daily_tasks': 'दैनिक कार्य',
  'teacher.content_management': 'समाचार व इवेंट',
  'teacher.notifications': 'सूचनाएँ'
};
