export const translations = {
  'nav.about': 'About',
  'nav.features': 'Features',
  'nav.impact': 'Impact',
  'nav.contact': 'Contact',
  'nav.login': 'Login',
  'nav.get_started': 'Get Started',
  'hero.title': 'Make Sustainable Farming Fun, Rewarding & Engaging',
  'hero.description': 'Join EcoVators to learn, contribute, and make a real impact on our planet through gamified challenges, community actions, and real-time tracking.',
  'hero.button': "Let's Get Started",
  'about.title': 'About EcoVators',
  'about.description': 'EcoVators is a gamified digital platform designed to inspire farmers to adopt eco-friendly practices through play, challenges and rewards. EcoVators motivates farmers - especially youth - to transition from unsustainable habits to progressive farming.',
  'about.goal': 'Our goal is to make Sustainable Agriculture not just necessity but an engaging journey - transforming it into a game, movement, and lifestyle.',
  'about.stats.active_farmers': '10,000+',
  'about.stats.active_farmers_label': 'Active Farmers',
  'about.stats.agri_experts': '500+',
  'about.stats.agri_experts_label': 'Agri-Experts',
  'about.stats.trees_planted': '50,000+',
  'about.stats.trees_planted_label': 'Trees Planted',
  'about.stats.challenges_completed': '100,000+',
  'about.stats.challenges_completed_label': 'Challenges Completed',
  'features.title': 'Platform Features',
  'features.gamified_learning': 'Gamified Learning',
  'features.gamified_learning_description': 'Earn XP, badges, and climb leaderboards while learning about environmental issues.',
  'features.community_chat': 'Community Chat',
  'features.community_chat_description': 'Connect with peers through real-time messaging with support for text, images, audio, and video.',
  'features.environmental_challenges': 'Environmental Challenges',
  'features.environmental_challenges_description': 'Participate in quizzes, activities, and real-world environmental actions.',
  'features.micro_courses': 'Micro-Courses',
  'features.micro_courses_description': 'Learn through bite-sized courses with progress tracking and certificates.',
  'features.events': 'Events',
  'features.events_description': 'Join environmental events organized by Cooperative Societies, NGOs, and community partners.',
  'features.geotag_uploads': 'Geotag Uploads',
  'features.geotag_uploads_description': 'Document your environmental actions with location-based verification.',
  'impact.title': 'Our Environmental Impact',
  'impact.metrics.co2_offset': '25,000',
  'impact.metrics.co2_offset_label': 'Tons of CO₂ Offset',
  'impact.metrics.waste_recycled': '75,000',
  'impact.metrics.waste_recycled_label': 'Kg of Waste Recycled',
  'impact.metrics.water_saved': '120,000',
  'impact.metrics.water_saved_label': 'Liters of Water Saved',
  'roles.title': 'Who Can Join EcoVators?',
  'roles.farmer': 'Farmers',
  'roles.farmer_description': 'Learn, participate in challenges, earn rewards, and make a real impact.',
  'roles.agri_expert': 'Agri-Experts',
  'roles.agri_expert_description': 'Create challenges, monitor farmers progress, and facilitate environmental activities.',
  'roles.cooperative_admin': 'Cooperative Society Admin',
  'roles.cooperative_admin_description': 'Manage your society\'s environmental initiatives and track overall impact.',
  'roles.ngo': 'NGOs',
  'roles.ngo_description': 'Organize events, collaborate with farmers, and expand your environmental impact.',
  'roles.company': 'Companies',
  'roles.company_description': 'Support environmental education through carbon credits and advertising partnerships.',
  'contact.title': 'Contact Us',
  'contact.email': 'ecovators.sih@gmail.com',
  'contact.phone': '+91 8141829957',
  'contact.address': 'Ahmedabad',
  'contact.send_message': 'Send Message',
  'footer.platform': 'Platform',
  'footer.features': 'Features',
  'footer.how_it_works': 'How It Works',
  'footer.pricing': 'Pricing',
  'footer.faq': 'FAQ',
  'footer.resources': 'Resources',
  'footer.blog': 'Blog',
  'footer.guides': 'Guides',
  'footer.events': 'Events',
  'footer.support': 'Support',
  'footer.company': 'Company',
  'footer.about_us': 'About Us',
  'footer.careers': 'Careers',
  'footer.partners': 'Partners',
  'footer.contact': 'Contact',
  'footer.legal': 'Legal',
  'footer.terms_of_service': 'Terms of Service',
  'footer.privacy_policy': 'Privacy Policy',
  'footer.cookie_policy': 'Cookie Policy',
  'footer.gdpr': 'GDPR',
  'footer.copyright': '© 2025 EcoVators. All rights reserved.',
  'role_modal.title': 'Select Your Role',
  'role_modal.description': 'Choose your role to continue to the appropriate registration page.',
  'role_modal.farmer': 'Farmer',
  'role_modal.farmer_description': 'Join challenges, earn rewards, track your environmental impact',
  'role_modal.agri_expert': 'Agri-Expert',
  'role_modal.agri_expert_description': 'Create challenges, monitor farmer progress, facilitate learning',
  'role_modal.cooperative_admin': 'Cooperative Society',
  'role_modal.cooperative_admin_description': 'Manage your society\'s environmental initiatives and track impact',
  'role_modal.ngo': 'NGO',
  'role_modal.ngo_description': 'Organize events, collaborate with farmers, expand your impact',
  'role_modal.company': 'Company',
  'role_modal.company_description': 'Support environmental sustainability through partnerships',
  'role_modal.government': 'Government',
  'role_modal.government_description': 'Monitor environmental initiatives and regulate carbon credit programs',
  'login_modal.title': 'Login',
  'login_modal.description': 'Sign in with your email and password',
  'login_modal.login_button': 'Login',
  'login_modal.or_login_with': 'Or login with',
  // --- Student Dashboard UI ---
  'nav.title': 'EcoVators',
  'nav.home': 'Home',
  'nav.logout': 'Logout',
  'student.nav.profile': 'Profile',
  'student.nav.challenges': 'Challenges',
  'student.nav.learning': 'Learning',
  'student.nav.community': 'Community',
  'student.nav.events': 'Events',
  // Sidebar
  'student.level': 'Level',
  'student.streak': 'day streak',
  'student.xp_points': 'XP Points',
  'student.carbon_credits': 'Carbon Credits',
  'student.to_next_level': 'to next level',
  'student.quick_actions': 'Quick Actions',
  'student.quick_actions.start_task': "Start Today's Task",
  'student.quick_actions.upload_proof': 'Upload Proof',
  'student.quick_actions.download_certificate': 'Download Certificate',
  'student.badges': 'Badges',
  'student.badge.tree_guardian': 'Tree Guardian',
  'student.badge.plastic_free_hero': 'Plastic-Free Hero',
  'student.badge.water_warrior': 'Water Warrior',
  'student.badge.energy_saver': 'Energy Saver',
  // Profile/Eco Impact
  'student.eco_impact': 'Eco Impact',
  'student.trees_planted': 'Trees Planted',
  'student.waste_reduced': 'Waste Reduced',
  'student.water_saved': 'Water Saved',
  'student.co2_offset': 'CO₂ Offset',
  // Goals
  'student.weekly_goals': 'Weekly Goals',
  'student.goal.complete_challenges': 'Complete 3 Challenges',
  'student.goal.study_micro_course': 'Study Micro-Course 40%',
  'student.goal.maintain_streak': 'Maintain Streak',
  // Challenges Section
  'student.active_challenges': 'Active Challenges',
  'student.challenge.plant_tree': 'Plant a Tree Challenge',
  'student.challenge.plant_tree_desc': 'Earn +50 XP and +20 carbon credits',
  'student.challenge.join': 'Join',
  'student.challenge.water_conservation': 'Water Conservation',
  'student.challenge.water_conservation_desc': 'Save 50 liters this week',
  'student.challenge.upload_proof': 'Upload Proof',
  'student.challenge.pending': 'Pending',
  'student.challenge.plastic_reduction': 'Plastic Reduction',
  'student.challenge.plastic_reduction_desc': 'One week plastic-free',
  'student.challenge.approved': 'Approved',
  // Micro-Courses
  'student.micro_courses': 'Micro-Courses',
  'student.course.climate_basics': 'Climate Basics',
  'student.course.climate_basics_desc': 'Intro to climate change and actions',
  'student.course.water_conservation': 'Water Conservation',
  'student.course.water_conservation_desc': 'Smart water usage',
  'student.course.waste_management': 'Waste Management',
  'student.course.waste_management_desc': 'Sorting and recycling',
  'student.continue_learning': 'Continue Learning',
  // Community/feed/chat
  'community.feed': 'Hacks & News',
  'community.post.composer.placeholder': 'Share a hack, photo or news...',
  'community.chat': 'Community Chat',
  'community.chat.input.placeholder': 'Type a message...',
  // Events/Uploads
  'events.upload.title': 'Upload with Geotag',
  'events.upload.get_location': 'Get Location',
  'events.upload.submit': 'Submit Proof',
  'events.upload.hint': 'Your Agri-Expert will review and approve/reject your proof.',
  // Leaderboard/Notifications/Footer
  'student.leaderboard': 'Leaderboard',
  'student.notifications': 'Notifications',
  'footer.farmer.title': 'Farmer',
  'footer.farmer.challenges': 'Challenges',
  'footer.farmer.learning': 'Learning',
  'footer.farmer.leaderboard': 'Leaderboard',
  'footer.community.title': 'Community',
  'footer.community.chat': 'Chat',
  'footer.community.events': 'Events',
  'footer.community.support': 'Support',
  'footer.legal.title': 'Legal',
  'footer.legal.terms': 'Terms',
  'footer.legal.privacy': 'Privacy',
  // --- Admin Dashboard ---
  'admin.nav.dashboard': 'Dashboard',
  'admin.nav.analytics': 'Analytics',
  'admin.nav.transactions': 'Transactions',
  'admin.nav.management': 'Management',
  'admin.nav.approvals': 'Approvals',
  'admin.quick_actions': 'Quick Actions',
  'admin.quick_actions.carbon_calculator': 'Carbon Calculator',
  'admin.quick_actions.export_data': 'Export Data (PDF)',
  'admin.quick_actions.add_agri_expert': 'Add Agri-Expert',
  'admin.quick_actions.add_farmer': 'Add Farmer',
  'admin.quick_actions.manage_content': 'Manage Content',
  'admin.recent_achievements': 'Recent Achievements',
  'admin.overview': 'Organization Overview',
  'admin.stats.total_farmers': 'Total Farmers',
  'admin.stats.active_agri_experts': 'Active Agri-Experts',
  'admin.stats.departments': 'Departments',
  'admin.stats.engagement_rate': 'Engagement Rate',
  'admin.environmental_impact': 'Environmental Impact',
  'admin.impact.trees_planted': 'Trees Planted',
  'admin.impact.waste_reduced': 'Waste Reduced (kg)',
  'admin.impact.water_saved': 'Water Saved (L)',
  'admin.impact.co2_offset': 'CO₂ Offset (kg)',
  'admin.department_performance': 'Crop Performance',
  'admin.analytics_overview': 'Analytics Overview',
  'admin.analytics.active_farmers': 'Active Farmers',
  'admin.analytics.avg_completion': 'Avg Completion',
  'admin.analytics.avg_time_spent': 'Avg Time Spent',
  'admin.analytics.submissions': 'Submissions',
  'admin.company_transactions': 'Company Transactions',
  'admin.government_transactions': 'Government Transactions',
  'admin.teacher_management': 'Agri-Expert Management',
  'admin.farmer_management': 'Farmer Management',
  'admin.content_management': 'Content Management',
  'admin.notifications': 'Notifications',
  'admin.ngo_event_approvals': 'NGO Event Approvals',

  // --- Company Dashboard ---
  'company.nav.dashboard': 'Dashboard',
  'company.nav.marketplace': 'Carbon Marketplace',
  'company.nav.advertisement': 'Advertisement',
  'company.nav.transactions': 'Transactions',
  'company.nav.analytics': 'Analytics',
  'company.quick_actions.title': 'Quick Actions',
  'company.quick_actions.buy_carbon_credits': 'Buy Carbon Credits',
  'company.quick_actions.create_campaign': 'Create Campaign',
  'company.quick_actions.view_analytics': 'View Analytics',
  'company.quick_actions.download_reports': 'Download Reports',
  'company.impact_overview': 'Environmental Impact',
  'company.impact.co2_offset': 'CO₂ Offset',
  'company.impact.trees_supported': 'Trees Supported',
  'company.marketplace.featured_credits': 'Featured Carbon Credits',
  'company.marketplace.available_credits': 'Available Credits',
  'company.marketplace.purchase_credits': 'Purchase Credits',
  'company.regional_performance.title': 'Regional Performance',
  'company.school_directory.title': 'Village Directory',
  'company.school_directory.search_villages': 'Search villages...',
  'company.teacher_directory.title': 'Agri-Experts Analytics',
  'company.teacher_directory.active_agri_experts': 'Active Agri-Experts',
  'company.teacher_directory.participation_rate': 'Participation Rate',
  'company.teacher_directory.avg_rating': 'Avg Rating',
  'company.participation_analytics.title': 'Participation Analytics',
  'company.participation_analytics.active_farmers': 'Active Farmers',
  'company.participation_analytics.avg_completion_rate': 'Avg Completion Rate',

  // --- Government Dashboard ---
  'government.nav.dashboard': 'Dashboard',
  'government.nav.transactions': 'Transactions',
  'government.nav.analytics': 'Analytics',
  'government.nav.reports': 'Reports',
  'government.quick_actions.title': 'Quick Actions',
  'government.quick_actions.view_reports': 'View Reports',
  'government.quick_actions.download_data': 'Download Data',
  'government.quick_actions.export_analytics': 'Export Analytics',
  'government.overview': 'Overview',
  'government.overview.villages': 'Villages',
  'government.overview.active_farmers': 'Active Farmers',
  'government.overview.active_agri_experts': 'Active Agri-Experts',
  'government.overview.ngo_partners': 'NGO Partners',
  'government.regional_performance.title': 'Regional Performance Overview',
  'government.transactions.title': 'Transactions',
  'government.transactions.date_time': 'Date & Time',
  'government.transactions.villages': 'Villages',
  'government.transactions.data_type': 'Data Type',
  'government.transactions.amount': 'Amount',
  'government.transactions.actions': 'Actions',
  'government.analytics.title': 'Analytics',
  'government.analytics.national_participation_change': 'National Participation Change',
  'government.analytics.environmental_impact': 'Environmental Impact',
  'government.analytics.budget_utilization': 'Budget Utilization',
  'government.reports.title': 'Reports',
  'government.reports.download_customized_reports': 'Download Customized Reports',
  'government.reports.recent_reports': 'Recent Reports',

  // --- NGO Dashboard ---
  'ngo.nav.dashboard': 'Dashboard',
  'ngo.nav.events': 'Events',
  'ngo.nav.schools': 'Villages',
  'ngo.nav.impact': 'Impact',
  'ngo.quick_actions': 'Quick Actions',
  'ngo.quick_actions.create_event': 'Create Event',
  'ngo.quick_actions.contact_villages': 'Contact Villages',
  'ngo.quick_actions.generate_report': 'Generate Report',
  'ngo.impact_summary': 'Impact Summary',
  'ngo.impact.events_organized': 'Events Organized',
  'ngo.impact.villages_partnered': 'Villages Partnered',
  'ngo.impact.farmers_reached': 'Farmers Reached',
  'ngo.dashboard.overview': 'Dashboard Overview',
  'ngo.event_management': 'Event Management',
  'ngo.event_management.add_event': 'Add New Event',
  'ngo.event_management.upcoming': 'Upcoming',
  'ngo.event_management.past': 'Past',
  'ngo.event_management.draft': 'Draft',
  'ngo.schools_section': 'Partner Villages & Societies',
  'ngo.schools_section.search_villages': 'Search villages...',
  'ngo.schools_section.active': 'Active',
  'ngo.schools_section.pending': 'Pending',
  'ngo.schools_section.contact': 'Contact',
  'ngo.impact_analytics': 'Environmental Impact Analytics',
  'ngo.impact_analytics.monthly': 'Monthly',
  'ngo.impact_analytics.yearly': 'Yearly',
  'ngo.impact_analytics.all_time': 'All Time',
  'ngo.impact_analytics.overall_impact': 'Overall Environmental Impact',
  'ngo.impact_analytics.carbon_footprint': 'Carbon Footprint Reduction',
  'ngo.impact_analytics.waste_management': 'Waste Management',
  'ngo.impact_analytics.water_conservation': 'Water Conservation',
  'ngo.impact_analytics.trees_planted': 'Trees Planted',
  'ngo.impact_analytics.export': 'Export Reports',
  'ngo.impact_analytics.export_pdf': 'PDF Report',
  'ngo.impact_analytics.export_excel': 'Excel Data',
  'ngo.impact_analytics.export_image': 'Infographics',

  // --- Teacher Dashboard ---
  'teacher.nav.dashboard': 'Dashboard',
  'teacher.nav.farmers': 'Farmers',
  'teacher.nav.challenges': 'Challenges',
  'teacher.nav.content': 'Content',
  'teacher.nav.analytics': 'Analytics',
  'teacher.stats.title': 'Quick Stats',
  'teacher.stats.total_farmers': 'Total Farmers',
  'teacher.stats.active_farmers': 'Active Farmers',
  'teacher.stats.pending_reviews': 'Pending Reviews',
  'teacher.stats.avg_completion': 'Avg Completion',
  'teacher.actions.title': 'Quick Actions',
  'teacher.actions.create_challenge': 'Create Challenge',
  'teacher.actions.add_news': 'Add News',
  'teacher.actions.create_event': 'Create Event',
  'teacher.actions.add_microcourse': 'Add Micro-Course',
  'teacher.dashboard.impact_overview': 'Environmental Impact Overview',
  'teacher.dashboard.trees_planted': 'Trees Planted',
  'teacher.dashboard.waste_reduced': 'Waste Reduced (kg)',
  'teacher.dashboard.water_saved': 'Water Saved (L)',
  'teacher.dashboard.co2_offset': 'CO₂ Offset (kg)',
  'teacher.dashboard.recent_activity': 'Recent Activity',
  'teacher.pending_reviews': 'Pending Reviews',
  'teacher.analytics.farmers_analytics': 'Farmers Analytics',
  'teacher.analytics.active_farmers': 'Active Farmers',
  'teacher.analytics.avg_completion_rate': 'Avg Completion Rate',
  'teacher.challenge_management': 'Challenge Management',
  'teacher.daily_tasks': 'Daily Tasks',
  'teacher.content_management': 'News & Events',
  'teacher.notifications': 'Notifications',
};
